name: racing
channels:
  - pytorch
  - nvidia  # For pytorch-cuda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # Conda packages
  - numpy
  - scipy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Ensure this matches your CUDA version
  - pygame
  - pyglet
  - box2d-py # Dependency for CarRacing
  - pip
  # Pip packages
  - pip:
    - gymnasium[box2d]>=0.28.0 # Includes the CarRacing-v3 environment
    - opencv-python
    - tensorboard 